"""统一错误码定义。

当前阶段先沉淀第一批最常用错误码常量，目的不是把所有错误一次性枚举完，
而是先把 API、Service、异常处理之间的错误语义稳定下来。

这样后续继续开发文档上传、合同审查、经营分析、Review、Trace 等模块时，
可以复用同一套错误码入口，避免字符串散落在各个文件里。
"""

# 通用请求与系统错误
REQUEST_VALIDATION_ERROR = "REQUEST_VALIDATION_ERROR"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
PERMISSION_DENIED = "PERMISSION_DENIED"
UNAUTHORIZED = "UNAUTHORIZED"
INVALID_AUTH_CONTEXT = "INVALID_AUTH_CONTEXT"

# 会话相关错误
CONVERSATION_NOT_FOUND = "CONVERSATION_NOT_FOUND"

# 文档相关错误
DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
DOCUMENT_PARSE_FAILED = "DOCUMENT_PARSE_FAILED"
DOCUMENT_NOT_PARSED = "DOCUMENT_NOT_PARSED"
DOCUMENT_INGEST_FAILED = "DOCUMENT_INGEST_FAILED"
DOCUMENT_NO_INDEXABLE_CHUNKS = "DOCUMENT_NO_INDEXABLE_CHUNKS"

# 检索相关错误
RETRIEVAL_FAILED = "RETRIEVAL_FAILED"

# LLM / Prompt 工程相关错误
# LLM_CALL_FAILED 表示模型网关调用阶段失败，例如缺少 API Key、网络超时或上游服务异常。
LLM_CALL_FAILED = "LLM_CALL_FAILED"
# LLM_OUTPUT_PARSE_FAILED 表示模型返回内容不是合法 JSON，尚未进入业务 Schema 校验。
LLM_OUTPUT_PARSE_FAILED = "LLM_OUTPUT_PARSE_FAILED"
# LLM_OUTPUT_VALIDATION_FAILED 表示 JSON 可解析，但不符合 Pydantic 结构化输出 Schema。
LLM_OUTPUT_VALIDATION_FAILED = "LLM_OUTPUT_VALIDATION_FAILED"

# 澄清相关错误
CLARIFICATION_NOT_FOUND = "CLARIFICATION_NOT_FOUND"

# 经营分析与 SQL 相关错误
ANALYTICS_RUN_NOT_FOUND = "ANALYTICS_RUN_NOT_FOUND"
ANALYTICS_QUERY_FAILED = "ANALYTICS_QUERY_FAILED"
ANALYTICS_METRIC_PERMISSION_DENIED = "ANALYTICS_METRIC_PERMISSION_DENIED"
ANALYTICS_DATA_SOURCE_PERMISSION_DENIED = "ANALYTICS_DATA_SOURCE_PERMISSION_DENIED"
ANALYTICS_DATA_SCOPE_DENIED = "ANALYTICS_DATA_SCOPE_DENIED"
ANALYTICS_FIELD_VISIBILITY_DENIED = "ANALYTICS_FIELD_VISIBILITY_DENIED"
ANALYTICS_EXPORT_NOT_FOUND = "ANALYTICS_EXPORT_NOT_FOUND"
ANALYTICS_EXPORT_FAILED = "ANALYTICS_EXPORT_FAILED"
ANALYTICS_REVIEW_NOT_FOUND = "ANALYTICS_REVIEW_NOT_FOUND"
ANALYTICS_REVIEW_NOT_REQUIRED = "ANALYTICS_REVIEW_NOT_REQUIRED"
ANALYTICS_REVIEW_INVALID_STATUS = "ANALYTICS_REVIEW_INVALID_STATUS"
SQL_GUARD_BLOCKED = "SQL_GUARD_BLOCKED"
SQL_EXECUTION_FAILED = "SQL_EXECUTION_FAILED"
